#1. create render.yaml
#2. sample code
services:
- type: web
  env: node
  name: fh-prod-backend1
  rep: https://github.com/nwrade/form-hub.git
  buildCommand: yarn && yarn build --filter=backend
  startCommand: cd app/backend; yarn start
  
  
- type: web
  env: static
  name: fh-prod-frontend1
  
- type: redis
  name: fh-prod-redis1

databases:
  name: fh-prod-db1
